### ISSUE TITLE
Feature request: different set of desktop icons per desktop

### ISSUE THREAD

**Issue by MrLightningTV** [sdias/win-10-virtual-desktop-enhancer#94] opened 2018-01-12 18:46 UTC
Not sure if this is possible, but I feel like virtual desktops could be way more powerfull with the ability for every virtual desktop to have its own set of desktop icons, that also remain when you reboot your system.

Love the enhancement btw. Thanks!

**Comment by sdias** [comment] 2018-01-31 19:32
Duplicate of #20

**Closed by sdias** 2018-01-31 19:32 UTC
Labels: feature request
