### ISSUE TITLE
Dual screen: different wallpaper per monitor

### ISSUE THREAD

**Issue by RobNO97** [sdias/win-10-virtual-desktop-enhancer#90] opened 2017-12-06 18:18 UTC
Hi, I use to have a different wallpaper on each monitor (I have 2). So it would be nice to be able using 2 wallpapers for each virtual desktop. Maybe there is already a way to put 2 picture path in the same "desktop" in the settings.ini file but I can't get it to work.
Dexpot do it, but I don't like the way it's not integrated  in windows 10. It just create virtual dektops on a windows virtual desktop but it does not use the windows 10 virtual desktops

**Comment by sdias** [comment] 2018-01-31 19:25
Duplicate of #12

**Closed by sdias** 2018-01-31 19:25 UTC
