### ISSUE TITLE
[Feature request] Visible desktop names when changing desktops AND wallpaper changing with multiple monitors

### ISSUE THREAD

**Issue by GitUT** [sdias/win-10-virtual-desktop-enhancer#79] opened 2017-09-12 18:48 UTC
Is it possible to have the user given names for virtual desktops visible when changing desktops?
Is it possible to have different default wallpapers for my different monitors?

Here is an imgur example from my PC. https://imgur.com/d0dgrJN
The wallpaper changed for both monitors and red circles is where it says just Desktop1, Desktop2, etc.

**Comment by GioBonvi** [comment] 2017-10-12 07:24
Hi @GitUT,

First of all let me apologize for taking so much time to come back at you on this issue.

> Is it possible to have the user given names for virtual desktops visible when changing desktops?

This was already asked in #55 and, as you can see, Windows does not let you edit these names (as for now)

> Is it possible to have different default wallpapers for my different monitors?

This was asked in #12.

I am closing this issue as it is a duplicate of the two aforementioned issues. Please follow them to receive any update on the matter,

Thank you for your patience.

**Closed by GioBonvi** 2017-10-12 07:24 UTC
